# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('power', models.TextField()),
                ('cubic_capacity', models.TextField()),
                ('torque', models.TextField()),
                ('top_speed', models.IntegerField()),
                ('acceleration', models.TextField()),
                ('average_consumption', models.TextField()),
                ('c02_emission', models.TextField()),
                ('emission_category', models.TextField()),
                ('start_stop_system', models.TextField()),
            ],
        ),
    ]
