# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='acceleration',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='average_consumption',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='c02_emission',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='cubic_capacity',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='emission_category',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='start_stop_system',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='top_speed',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='engine',
            name='torque',
            field=models.CharField(max_length=4096),
        ),
    ]
