# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enqueue', '0004_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
